"""
README Service — Reads the base README.md and writes an updated UPDATED_README.md
with a new '## 🔄 Latest Updates' section appended.
"""

import os
from datetime import datetime

BASE_README = os.path.join(os.path.dirname(__file__), "..", "..", "README.md")
UPDATED_README = os.path.join(os.path.dirname(__file__), "..", "..", "UPDATED_README.md")


def read_readme() -> str:
    """Read the base README.md, return empty string if not found."""
    try:
        with open(BASE_README, "r", encoding="utf-8") as f:
            return f.read()
    except FileNotFoundError:
        return "# Project README\n\nNo README found.\n"


def build_updates_section(analysis: dict, repo_info: dict) -> str:
    """Build the '## 🔄 Latest Updates' markdown section."""
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    repo_name = repo_info.get("repo_name", "this project")

    lines = [
        "",
        "---",
        "",
        "## 🔄 Latest Updates",
        "",
        f"> _Auto-generated by RepoSense AI on {now}_",
        "",
        f"### 📊 Change Summary for `{repo_name}`",
        "",
        f"- **Pull Requests Analyzed:** {analysis['total_prs']}",
        f"- **Files Affected:** {analysis['files_affected']}",
        f"- **Contributors:** {', '.join('@' + c for c in analysis['contributors'])}",
        f"- **Breaking Changes:** {'⚠️ Yes — review required' if analysis['has_breaking_changes'] else '✅ None'}",
        "",
    ]

    # Changelog table
    lines += [
        "### 📋 Recent Merged Pull Requests",
        "",
        "| PR | Title | Author | Breaking |",
        "|---|---|---|---|",
    ]
    for entry in analysis["changelog"]:
        breaking_flag = "⚠️ Yes" if entry["breaking"] else "✅ No"
        lines.append(
            f"| {entry['id']} | {entry['title']} | @{entry['author']} | {breaking_flag} |"
        )

    lines.append("")

    # Breaking changes section
    if analysis["has_breaking_changes"]:
        lines += [
            "### ⚠️ Breaking Changes — Action Required",
            "",
        ]
        for bc in analysis["breaking_changes"]:
            lines += [
                f"**{bc['pr']}: {bc['title']}**",
                f"- {bc['note']}",
                "",
            ]

    # Setup instructions
    lines += [
        "### 🚀 Setup Instructions",
        "",
    ]
    for step in analysis["setup_instructions"]:
        lines.append(f"1. {step}")

    lines += [
        "",
        "### 💬 What Changed (Plain English)",
        "",
        analysis["simple_explanation"],
        "",
    ]

    return "\n".join(lines)


def update_readme(analysis: dict, repo_info: dict) -> dict:
    """
    Read README.md, append the latest-updates section, write UPDATED_README.md.
    Returns a dict with the path and preview of the updated content.
    """
    original_content = read_readme()
    updates_section = build_updates_section(analysis, repo_info)
    updated_content = original_content.rstrip() + "\n" + updates_section

    try:
        with open(UPDATED_README, "w", encoding="utf-8") as f:
            f.write(updated_content)
        success = True
        message = "UPDATED_README.md written successfully."
    except Exception as e:
        success = False
        message = f"Failed to write UPDATED_README.md: {e}"

    # Return a preview (first 800 chars of the new section)
    preview = updates_section[:900] + ("..." if len(updates_section) > 900 else "")

    return {
        "success": success,
        "message": message,
        "output_file": "UPDATED_README.md",
        "original_lines": len(original_content.splitlines()),
        "updated_lines": len(updated_content.splitlines()),
        "preview": preview,
    }
